exe : main.cpp vector.o UpperTraingularMatrix.o
	g++ main.cpp vector.o UpperTraingularMatrix.o -o main

UpperTraingularMatrix.o : UpperTraingularMatrix.cpp
	g++ -c UpperTraingularMatrix.cpp
vector.o:vector.cpp
	g++ -c vector.cpp